right_format = """$time"""

[git_status]
format = '([\[$conflicted$stashed$deleted$renamed$modified$staged$untracked$ahead_behind\]]($style) )'
stashed = "[^$count](bold yellow)"
deleted = "[âœ˜$count](bold red)"
modified = "[!$count](bold purple)"
renamed = "[Â»$count](bold purple)"
untracked = "[?$count](bold green)"
staged = "[+$count](bold blue)"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
style = "bold"

[shell]
fish_indicator = "ïœ¹"
bash_indicator = "Î²"
zsh_indicator = "Î¶"
nu_indicator = "Î½"
powershell_indicator = "ï‘ _"
unknown_indicator = "mystery shell"
style = "cyan bold"
disabled = false

[time]
disabled = false
format = 'ðŸ•™[\[$time\]]($style) '
time_format = "%T"
utc_time_offset = "+5.5"